//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeDecide.Models.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.UserResponses = new HashSet<UserResponse>();
            this.Responses = new HashSet<Response>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public bool IsActive { get; set; }
        public bool FreeResponseEnabled { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<UserResponse> UserResponses { get; set; }
        public virtual ICollection<Response> Responses { get; set; }
        public virtual User User { get; set; }
    }
}
